--SQL file

DELETE MEDICO_ENTITY;

INSERT INTO MEDICO_ENTITY(ID, NOMBRE, APELLIDO, REGISTRO_MEDICO, ESPECIALIDAD) VALUES (1,'Juan Jose', 'Rodríguez Ortiz', 'FC3578K', 'Anestesiología');
INSERT INTO MEDICO_ENTITY(ID, NOMBRE, APELLIDO, REGISTRO_MEDICO, ESPECIALIDAD) VALUES (2,'María Paula', 'Sarmiento Mancipe', 'DE7825', 'Medicina Interna');
